"""
clear_calendar.py — Deletes all events in a date range from a Google Calendar.

Reads credentials and calendar ID from config.py (which loads .env).
Defaults to wiping June 2026 — the range generated by generate_calendar.py.
Override via --start and --end flags (ISO date strings, e.g. 2026-06-01).

Usage:
    python3 clear_calendar.py
    python3 clear_calendar.py --calendar malik@moreclientsco.com
    python3 clear_calendar.py --start 2026-06-01 --end 2026-07-01
"""

import argparse
import os
from datetime import date, datetime, timezone

from google.oauth2.service_account import Credentials
from googleapiclient.discovery import build

# Import shared config so credential path and calendar ID stay in one place
from config import DEFAULT_CALENDAR_ID, SCOPES, SERVICE_ACCOUNT_FILE


# --- Helpers -----------------------------------------------------------------


def build_service() -> object:
    """Authenticate and return a Google Calendar API service client."""
    key_path = os.path.expanduser(SERVICE_ACCOUNT_FILE)
    creds = Credentials.from_service_account_file(key_path, scopes=SCOPES)
    return build("calendar", "v3", credentials=creds)


def list_events(service, calendar_id: str, time_min: str, time_max: str) -> list:
    """Return all events in the calendar between time_min and time_max (UTC ISO strings)."""
    events = []
    page_token = None

    while True:
        result = service.events().list(
            calendarId=calendar_id,
            timeMin=time_min,
            timeMax=time_max,
            maxResults=250,
            singleEvents=True,
            orderBy="startTime",
            pageToken=page_token,
        ).execute()

        events.extend(result.get("items", []))
        page_token = result.get("nextPageToken")
        if not page_token:
            break

    return events


def delete_events(service, calendar_id: str, events: list) -> tuple[int, int]:
    """Delete each event; return (deleted_count, failed_count)."""
    deleted = 0
    failed = 0

    for event in events:
        summary = event.get("summary", "untitled")
        event_date = event.get("start", {}).get("date", "unknown")
        try:
            service.events().delete(
                calendarId=calendar_id,
                eventId=event["id"],
            ).execute()
            print(f"  Deleted: {summary} on {event_date}")
            deleted += 1
        except Exception as exc:
            print(f"  FAILED:  {summary} on {event_date} — {exc}")
            failed += 1

    return deleted, failed


# --- Main --------------------------------------------------------------------


def main() -> None:
    """Parse args, delete all matching events, verify calendar is clear."""
    parser = argparse.ArgumentParser(
        description="Delete all events in a Google Calendar date range."
    )
    parser.add_argument(
        "--calendar",
        default=DEFAULT_CALENDAR_ID,
        help="Calendar ID (default: from config/.env)",
    )
    parser.add_argument(
        "--start",
        default="2026-06-01",
        help="Start date inclusive, ISO format YYYY-MM-DD (default: 2026-06-01)",
    )
    parser.add_argument(
        "--end",
        default="2026-07-01",
        help="End date exclusive, ISO format YYYY-MM-DD (default: 2026-07-01)",
    )
    args = parser.parse_args()

    # Convert date strings to UTC ISO timestamps required by the API
    time_min = f"{args.start}T00:00:00Z"
    time_max = f"{args.end}T00:00:00Z"

    print(f"\nCalendar : {args.calendar}")
    print(f"Range    : {args.start} → {args.end} (exclusive)")
    print("-" * 50)

    # --- Auth -----------------------------------------------------------------
    service = build_service()

    # --- List -----------------------------------------------------------------
    print("Fetching events…")
    events = list_events(service, args.calendar, time_min, time_max)
    print(f"Found {len(events)} event(s) to delete\n")

    if not events:
        print("Nothing to delete. Exiting.")
        return

    # --- Delete ---------------------------------------------------------------
    deleted, failed = delete_events(service, args.calendar, events)

    print(f"\n{'=' * 50}")
    print(f"  Deleted : {deleted}")
    print(f"  Failed  : {failed}")
    print(f"{'=' * 50}\n")

    # --- Verify ---------------------------------------------------------------
    print("Verifying calendar is clear…")
    remaining = list_events(service, args.calendar, time_min, time_max)

    if not remaining:
        print("Calendar cleared successfully. Zero events remain in range.")
    else:
        print(f"WARNING: {len(remaining)} event(s) still remain:")
        for evt in remaining:
            print(
                f"  - {evt.get('summary', 'untitled')} "
                f"on {evt.get('start', {}).get('date', 'unknown')}"
            )


if __name__ == "__main__":
    main()
